using Nucleus.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nucleus.Game
{
    public interface IAbility : IDeletable
    {
        /// <summary>
        /// Populate the active element's AvailableActions component with actions
        /// generated by this ability
        /// </summary>
        /// <param name="context"></param>
        void PopulateActions(TurnContext context);
    }
}
